events {}

http {
    # Ограничение количества запросов: не более 10 запросов в минуту с одного IP
    limit_req_zone $binary_remote_addr zone=partner_limit:10m rate=10r/m;

    # Настройка upstream для балансировки нагрузки
    upstream backend_servers {
        server 127.0.0.1:8080;
        server 127.0.0.1:8081;
        server 127.0.0.1:8082;
    }

    server {
        listen 80;

        location / {
            # Применение лимитирования запросов
            limit_req zone=partner_limit;
            limit_req_status 429;

            proxy_pass http://backend_servers;
        }

    }
}



